"""KiCad文件导出器 — 生成 .kicad_sch 和 .kicad_pcb 文件"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..utils.helpers import generate_uuid
from ..core.placer import PlacementResult, PlacedComponent
from ..core.router import RoutingResult
from ..core.generator import SchematicDesign


class KiCadExporter:
    """
    KiCad文件导出器。
    
    将 SchematicDesign + PlacementResult + RoutingResult
    导出为 KiCad 8/9 兼容的 .kicad_sch 和 .kicad_pcb 文件。
    
    KiCad文件格式为S-expression (类似Lisp)。
    """
    
    def __init__(self, design: SchematicDesign):
        self.design = design
    
    def export_schematic(
        self,
        output_dir: str,
        placement: Optional[PlacementResult] = None,
    ) -> str:
        """
        导出KiCad原理图文件 (.kicad_sch)。
        
        Args:
            output_dir: 输出目录
            placement: 布局结果（可选，用于设置元件位置）
        
        Returns:
            输出文件路径
        """
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{self.design.title}.kicad_sch")
        
        # 建立元件位置映射
        pos_map: dict[str, tuple[float, float]] = {}
        if placement:
            for comp in placement.components:
                pos_map[comp.reference] = (comp.x, comp.y)
        
        # KiCad坐标转换（mm → mils, Y轴翻转）
        def to_kicad_coord(x_mm: float, y_mm: float) -> tuple[float, float]:
            return x_mm * 39.3701, y_mm * 39.3701
        
        lines: list[str] = []
        lines.append(f'(kicad_sch (version 20231120) (generator "code2pcb v0.1.0")')
        lines.append("")
        
        # UUID
        lines.append(f'  (uuid "{generate_uuid()}")')
        lines.append("")
        
        # 纸张
        lines.append('  (paper "A4")')
        lines.append("")
        
        # 标题栏
        lines.append('  (title_block')
        lines.append(f'    (title "{self.design.title}")')
        lines.append(f'    (date "{datetime.now().strftime("%Y-%m-%d")}")')
        lines.append('    (rev "0.1.0")')
        lines.append('    (company "Generated by code2pcb")')
        lines.append('  )')
        lines.append("")
        
        # 库符号（占位）
        lines.append('  (lib_symbols')
        for comp in self.design.components:
            lib_id = f"{comp.library}:{comp.value}"
            lines.append(f'    (symbol "{lib_id}" (in_bom yes) (on_board yes))')
        lines.append('  )')
        lines.append("")
        
        # 器件实例
        for i, comp in enumerate(self.design.components):
            x_mm, y_mm = pos_map.get(comp.reference, (30.0 + i * 20, 50.0))
            x_ki, y_ki = to_kicad_coord(x_mm, y_mm)
            
            lib_id = f"{comp.library}:{comp.value}"
            lines.append(f'  (symbol (lib_id "{lib_id}") (at {x_ki:.1f} {y_ki:.1f} 0)')
            lines.append(f'    (uuid "{generate_uuid()}")')
            lines.append(f'    (property "Reference" "{comp.reference}" (at {x_ki:.1f} {y_ki - 200:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27))))')
            lines.append(f'    (property "Value" "{comp.value}" (at {x_ki:.1f} {y_ki + 200:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27))))')
            lines.append(f'    (property "Footprint" "{comp.footprint}" (at {x_ki:.1f} {y_ki - 350:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27)) hide))')
            lines.append('    (in_bom yes) (on_board yes)')
            lines.append('  )')
            lines.append("")
        
        # 电源符号
        lines.append('  (symbol (lib_id "power:VCC") (at 200 100 0)')
        lines.append(f'    (uuid "{generate_uuid()}")')
        lines.append('    (property "Reference" "#PWR01" (at 200 90 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('    (property "Value" "VCC" (at 200 120 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('  )')
        lines.append("")
        lines.append('  (symbol (lib_id "power:GND") (at 200 200 0)')
        lines.append(f'    (uuid "{generate_uuid()}")')
        lines.append('    (property "Reference" "#PWR02" (at 200 190 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('    (property "Value" "GND" (at 200 220 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('  )')
        lines.append("")
        
        # 连线（VCC/GND示意）
        if self.design.components:
            first_comp = self.design.components[0]
            x_mm, _ = pos_map.get(first_comp.reference, (30.0, 50.0))
            x_ki = x_mm * 39.3701
            
            # VCC连线
            lines.append(f'  (wire (pts (xy {x_ki:.0f} 100) (xy {x_ki:.0f} 200)) (stroke (width 0) (type default)) (uuid "{generate_uuid()}"))')
            # GND连线
            lines.append(f'  (wire (pts (xy {x_ki:.0f} 200) (xy {x_ki:.0f} 300)) (stroke (width 0) (type default)) (uuid "{generate_uuid()}"))')
            lines.append("")
        
        # 网络
        lines.append('  (nets')
        lines.append(f'    (net (code 0) (name "")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append(f'    (net (code 1) (name "VCC")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append(f'    (net (code 2) (name "GND")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append('  )')
        lines.append("")
        
        # Sheet instances
        lines.append('  (sheet_instances')
        lines.append('    (path "/" (page "1"))')
        lines.append('  )')
        lines.append(')')
        
        content = "\n".join(lines)
        Path(output_path).write_text(content, encoding="utf-8")
        
        return output_path
    
    def export_pcb(
        self,
        output_dir: str,
        placement: Optional[PlacementResult] = None,
        routing: Optional[RoutingResult] = None,
    ) -> str:
        """
        导出KiCad PCB文件 (.kicad_pcb) — 含真实焊盘、丝印、走线。
        
        Args:
            output_dir: 输出目录
            placement: 布局结果
            routing: 布线结果
        
        Returns:
            输出文件路径
        """
        from .footprints import get_footprint_def
        
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{self.design.title}.kicad_pcb")
        
        board_w = placement.board_width if placement else 100.0
        board_h = placement.board_height if placement else 80.0
        
        # 构建网络表
        net_map: dict[str, int] = {"": 0, "VCC": 1, "GND": 2}
        # 从 design.nets 补充
        for net in self.design.nets:
            if net.name not in net_map:
                net_map[net.name] = len(net_map)
        # 从 routing 补充信号网络
        if routing:
            for track in routing.tracks:
                if track.net and track.net not in net_map:
                    net_map[track.net] = len(net_map)
        
        lines: list[str] = []
        lines.append(f'(kicad_pcb (version 20221018) (generator "code2pcb v0.1.0")')
        lines.append("")
        lines.append(f'  (general (thickness 1.6))')
        lines.append("")
        
        # 纸张
        lines.append(f'  (paper "A4")')
        lines.append("")
        
        # 层定义
        layers = [
            (0, "F.Cu", "signal"),
            (31, "B.Cu", "signal"),
            (32, "B.Adhes", "user"),
            (33, "F.Adhes", "user"),
            (34, "B.Paste", "user"),
            (35, "F.Paste", "user"),
            (36, "B.SilkS", "user"),
            (37, "F.SilkS", "user"),
            (38, "B.Mask", "user"),
            (39, "F.Mask", "user"),
            (40, "Dwgs.User", "user"),
            (41, "Cmts.User", "user"),
            (42, "Eco1.User", "user"),
            (43, "Eco2.User", "user"),
            (44, "Edge.Cuts", "user"),
            (45, "Margin", "user"),
            (46, "B.CrtYd", "user"),
            (47, "F.CrtYd", "user"),
            (48, "B.Fab", "user"),
            (49, "F.Fab", "user"),
        ]
        lines.append(f'  (layers')
        for code, name, layer_type in layers:
            lines.append(f'    (layer {code} "{name}" {layer_type} (layer_type {layer_type}))')
        lines.append(f'  )')
        lines.append("")
        
        # 板子边框
        margin = 2.0
        edge_uuids = [generate_uuid() for _ in range(4)]
        lines.append(f'  (gr_line (start {margin} {margin}) (end {board_w - margin} {margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{edge_uuids[0]}"))')
        lines.append(f'  (gr_line (start {board_w - margin} {margin}) (end {board_w - margin} {board_h - margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{edge_uuids[1]}"))')
        lines.append(f'  (gr_line (start {board_w - margin} {board_h - margin}) (end {margin} {board_h - margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{edge_uuids[2]}"))')
        lines.append(f'  (gr_line (start {margin} {board_h - margin}) (end {margin} {margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{edge_uuids[3]}"))')
        lines.append("")
        
        # Setup
        lines.append(f'  (setup')
        lines.append(f'    (pad_to_mask_clearance 0.05)')
        lines.append(f'    (grid_origin 0 0)')
        lines.append(f'    (pcbplotparams')
        lines.append(f'      (layerselection 0x00010fc_ffffffff)')
        lines.append(f'      (plotframeref false)')
        lines.append(f'      (usegerberextensions false)')
        lines.append(f'      (usegerberattributes true)')
        lines.append(f'      (usegerberadvancedattributes true)')
        lines.append(f'      (creategerberjobfile true)')
        lines.append(f'      (dashed_line_dash_ratio 12.000000)')
        lines.append(f'      (dashed_line_gap_ratio 3.000000)')
        lines.append(f'      (svgprecision 6)')
        lines.append(f'      (plotframeref false)')
        lines.append(f'      (mode 1)')
        lines.append(f'      (useauxorigin false)')
        lines.append(f'      (hpglpennumber 1)')
        lines.append(f'      (hpglspeed 20)')
        lines.append(f'      (hpglpeldiameter 15.000000)')
        lines.append(f'      (drcpolygon true)')
        lines.append(f'      (drcminmillesspace 0.5)')
        lines.append(f'    )')
        lines.append(f'  )')
        lines.append("")
        
        # 网络声明
        for net_name, net_code in sorted(net_map.items(), key=lambda x: x[1]):
            lines.append(f'  (net {net_code} "{net_name}")')
        lines.append("")
        
        # 器件封装（真实焊盘）
        if placement:
            for comp in placement.components:
                fp_uuid = generate_uuid()
                lines.append(f'  (footprint "{comp.footprint}" (layer "F.Cu")')
                lines.append(f'    (tstamp "{fp_uuid}")')
                lines.append(f'    (at {comp.x:.2f} {comp.y:.2f} {comp.rotation:.0f})')
                lines.append(f'    (descr "{comp.footprint}")')
                lines.append(f'    (tags "code2pcb")')
                
                # Reference
                lines.append(f'    (fp_text reference "{comp.reference}" (at 0 -2 0)')
                lines.append(f'      (layer "F.SilkS")')
                lines.append(f'      (effects (font (size 1 1) (thickness 0.15))))')
                # Value
                lines.append(f'    (fp_text value "{comp.value}" (at 0 2 0)')
                lines.append(f'      (layer "F.Fab")')
                lines.append(f'      (effects (font (size 1 1) (thickness 0.15))))')
                
                # 获取封装定义，生成真实焊盘
                fp_def = get_footprint_def(comp.footprint)
                if fp_def:
                    # Court yard
                    cx, cy = fp_def.courtyard[:2]
                    cw, ch = fp_def.courtyard[2:]
                    lines.append(f'    (fp_poly (pts')
                    pad_cu = fp_def.courtyard[2]
                    pad_cv = fp_def.courtyard[3]
                    for px, py in [
                        (cx, cy), (cx + cw, cy), (cx + cw, cy + ch), (cx, cy + ch)
                    ]:
                        lines.append(f'      (xy {px:.2f} {py:.2f})')
                    lines.append(f'    ) (layer "F.CrtYd") (width 0.05) (fill none) (tstamp "{generate_uuid()}"))')
                    
                    # Body silkscreen
                    if fp_def.body_rect:
                        bx, by, bw, bh = fp_def.body_rect
                        lines.append(f'    (fp_rect (start {bx:.2f} {by:.2f}) (end {bx + bw:.2f} {by + bh:.2f})')
                        lines.append(f'      (layer "F.SilkS") (width 0.12) (fill none) (tstamp "{generate_uuid()}"))')
                    
                    # Pads
                    for i, pad in enumerate(fp_def.pads):
                        pad_uuid = generate_uuid()
                        layers_str = " ".join(f'"{l}"' for l in pad.layers)
                        
                        # 分配网络：pin 1→VCC, pin 2→GND（简化示意）
                        net_code = 0
                        if i == 0 and "VCC" in net_map:
                            net_code = net_map["VCC"]
                        elif i == 1 and "GND" in net_map:
                            net_code = net_map["GND"]
                        
                        if pad.pad_type == "tht":
                            drill_str = f'(drill {pad.drill:.2f})' if pad.drill else ""
                            lines.append(f'    (pad "{pad.name}" {pad.pad_type} {pad.shape} (at {pad.at[0]:.2f} {pad.at[1]:.2f}) (size {pad.size[0]:.2f} {pad.size[1]:.2f}) {drill_str} (layers {layers_str}) (net {net_code}) (tstamp "{pad_uuid}"))')
                        elif pad.shape == "circle":
                            lines.append(f'    (pad "{pad.name}" {pad.pad_type} {pad.shape} (at {pad.at[0]:.2f} {pad.at[1]:.2f}) (size {pad.size[0]:.2f} {pad.size[1]:.2f}) (layers {layers_str}) (net {net_code}) (tstamp "{pad_uuid}"))')
                        else:
                            rr = pad.roundrect_rratio
                            lines.append(f'    (pad "{pad.name}" {pad.pad_type} {pad.shape} (at {pad.at[0]:.2f} {pad.at[1]:.2f}) (size {pad.size[0]:.2f} {pad.size[1]:.2f}) (layers {layers_str}) (roundrect_rratio {rr}) (net {net_code}) (tstamp "{pad_uuid}"))')
                else:
                    # Fallback: 单个焊盘
                    lines.append(f'    (pad "1" smd roundrect (at 0 0) (size 1 1) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25) (net {net_map.get("VCC", 0)}) (tstamp "{generate_uuid()}"))')
                
                lines.append('  )')
                lines.append("")
        
        # 走线
        if routing:
            for track in routing.tracks:
                net_code = net_map.get(track.net, 0)
                lines.append(f'  (segment (start {track.start_x:.2f} {track.start_y:.2f}) (end {track.end_x:.2f} {track.end_y:.2f}) (width {track.width:.2f}) (layer "{track.layer}") (net {net_code}))')
            
            # 过孔
            for via in routing.vias:
                via_uuid = generate_uuid()
                lines.append(f'  (via (at {via.x:.2f} {via.y:.2f}) (size {via.size:.2f}) (drill {via.drill:.2f}) (layers "F.Cu" "B.Cu") (net {net_map.get("VCC", 0)}) (tstamp "{via_uuid}"))')
            
            lines.append("")
        
        # 目标 / 网络
        lines.append('  (target')
        lines.append(f'    (at {board_w / 2:.2f} {board_h / 2:.2f} 0)')
        lines.append(f'    (size 1.27 1.27)')
        lines.append(f'    (layers "F.Cu" "F.Mask")')
        lines.append(f'    (net {net_map.get("GND", 2)})')
        lines.append(f'    (tstamp "{generate_uuid()}")')
        lines.append(f'    (drill raw 0.8)')
        lines.append(f'  )')
        lines.append("")
        
        lines.append(')')
        
        content = "\n".join(lines)
        Path(output_path).write_text(content, encoding="utf-8")
        
        return output_path
