"""KiCad文件导出器 — 生成 .kicad_sch 和 .kicad_pcb 文件"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..utils.helpers import generate_uuid
from ..core.placer import PlacementResult, PlacedComponent
from ..core.router import RoutingResult
from ..core.generator import SchematicDesign


class KiCadExporter:
    """
    KiCad文件导出器。
    
    将 SchematicDesign + PlacementResult + RoutingResult
    导出为 KiCad 8/9 兼容的 .kicad_sch 和 .kicad_pcb 文件。
    
    KiCad文件格式为S-expression (类似Lisp)。
    """
    
    def __init__(self, design: SchematicDesign):
        self.design = design
    
    def export_schematic(
        self,
        output_dir: str,
        placement: Optional[PlacementResult] = None,
    ) -> str:
        """
        导出KiCad原理图文件 (.kicad_sch)。
        
        Args:
            output_dir: 输出目录
            placement: 布局结果（可选，用于设置元件位置）
        
        Returns:
            输出文件路径
        """
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{self.design.title}.kicad_sch")
        
        # 建立元件位置映射
        pos_map: dict[str, tuple[float, float]] = {}
        if placement:
            for comp in placement.components:
                pos_map[comp.reference] = (comp.x, comp.y)
        
        # KiCad坐标转换（mm → mils, Y轴翻转）
        def to_kicad_coord(x_mm: float, y_mm: float) -> tuple[float, float]:
            return x_mm * 39.3701, y_mm * 39.3701
        
        lines: list[str] = []
        lines.append(f'(kicad_sch (version 20231120) (generator "PCB Forge v0.1.0")')
        lines.append("")
        
        # UUID
        lines.append(f'  (uuid "{generate_uuid()}")')
        lines.append("")
        
        # 纸张
        lines.append('  (paper "A4")')
        lines.append("")
        
        # 标题栏
        lines.append('  (title_block')
        lines.append(f'    (title "{self.design.title}")')
        lines.append(f'    (date "{datetime.now().strftime("%Y-%m-%d")}")')
        lines.append('    (rev "0.1.0")')
        lines.append('    (company "Generated by PCB Forge")')
        lines.append('  )')
        lines.append("")
        
        # 库符号（占位）
        lines.append('  (lib_symbols')
        for comp in self.design.components:
            lib_id = f"{comp.library}:{comp.value}"
            lines.append(f'    (symbol "{lib_id}" (in_bom yes) (on_board yes))')
        lines.append('  )')
        lines.append("")
        
        # 器件实例
        for i, comp in enumerate(self.design.components):
            x_mm, y_mm = pos_map.get(comp.reference, (30.0 + i * 20, 50.0))
            x_ki, y_ki = to_kicad_coord(x_mm, y_mm)
            
            lib_id = f"{comp.library}:{comp.value}"
            lines.append(f'  (symbol (lib_id "{lib_id}") (at {x_ki:.1f} {y_ki:.1f} 0)')
            lines.append(f'    (uuid "{generate_uuid()}")')
            lines.append(f'    (property "Reference" "{comp.reference}" (at {x_ki:.1f} {y_ki - 200:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27))))')
            lines.append(f'    (property "Value" "{comp.value}" (at {x_ki:.1f} {y_ki + 200:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27))))')
            lines.append(f'    (property "Footprint" "{comp.footprint}" (at {x_ki:.1f} {y_ki - 350:.1f} 0)')
            lines.append(f'      (effects (font (size 1.27 1.27)) hide))')
            lines.append('    (in_bom yes) (on_board yes)')
            lines.append('  )')
            lines.append("")
        
        # 电源符号
        lines.append('  (symbol (lib_id "power:VCC") (at 200 100 0)')
        lines.append(f'    (uuid "{generate_uuid()}")')
        lines.append('    (property "Reference" "#PWR01" (at 200 90 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('    (property "Value" "VCC" (at 200 120 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('  )')
        lines.append("")
        lines.append('  (symbol (lib_id "power:GND") (at 200 200 0)')
        lines.append(f'    (uuid "{generate_uuid()}")')
        lines.append('    (property "Reference" "#PWR02" (at 200 190 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('    (property "Value" "GND" (at 200 220 0)')
        lines.append('      (effects (font (size 1.27 1.27))))')
        lines.append('  )')
        lines.append("")
        
        # 连线（VCC/GND示意）
        if self.design.components:
            first_comp = self.design.components[0]
            x_mm, _ = pos_map.get(first_comp.reference, (30.0, 50.0))
            x_ki = x_mm * 39.3701
            
            # VCC连线
            lines.append(f'  (wire (pts (xy {x_ki:.0f} 100) (xy {x_ki:.0f} 200)) (stroke (width 0) (type default)) (uuid "{generate_uuid()}"))')
            # GND连线
            lines.append(f'  (wire (pts (xy {x_ki:.0f} 200) (xy {x_ki:.0f} 300)) (stroke (width 0) (type default)) (uuid "{generate_uuid()}"))')
            lines.append("")
        
        # 网络
        lines.append('  (nets')
        lines.append(f'    (net (code 0) (name "")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append(f'    (net (code 1) (name "VCC")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append(f'    (net (code 2) (name "GND")')
        lines.append(f'      (uuid "{generate_uuid()}")')
        lines.append('    )')
        lines.append('  )')
        lines.append("")
        
        # Sheet instances
        lines.append('  (sheet_instances')
        lines.append('    (path "/" (page "1"))')
        lines.append('  )')
        lines.append(')')
        
        content = "\n".join(lines)
        Path(output_path).write_text(content, encoding="utf-8")
        
        return output_path
    
    def export_pcb(
        self,
        output_dir: str,
        placement: Optional[PlacementResult] = None,
        routing: Optional[RoutingResult] = None,
    ) -> str:
        """
        导出KiCad PCB文件 (.kicad_pcb)。
        
        Args:
            output_dir: 输出目录
            placement: 布局结果
            routing: 布线结果
        
        Returns:
            输出文件路径
        """
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{self.design.title}.kicad_pcb")
        
        board_w = placement.board_width if placement else 100.0
        board_h = placement.board_height if placement else 80.0
        
        lines: list[str] = []
        lines.append(f'(kicad_pcb (version 20221018) (generator "PCB Forge v0.1.0")')
        lines.append("")
        lines.append(f'  (general (thickness 1.6))')
        lines.append("")
        
        # 板子边框
        margin = 2.0
        lines.append(f'  (gr_line (start {margin} {margin}) (end {board_w - margin} {margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{generate_uuid()}"))')
        lines.append(f'  (gr_line (start {board_w - margin} {margin}) (end {board_w - margin} {board_h - margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{generate_uuid()}"))')
        lines.append(f'  (gr_line (start {board_w - margin} {board_h - margin}) (end {margin} {board_h - margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{generate_uuid()}"))')
        lines.append(f'  (gr_line (start {margin} {board_h - margin}) (end {margin} {margin}) (layer "Edge.Cuts") (width 0.1) (tstamp "{generate_uuid()}"))')
        lines.append("")
        
        # 板子尺寸
        lines.append(f'    (setup')
        lines.append(f'      (pad_to_mask_clearance 0.05)')
        lines.append(f'      (pcbplotparams')
        lines.append(f'        (layerselection 0x00010fc_ffffffff)')
        lines.append(f'        (plotframeref false)')
        lines.append(f'        (usegerberextensions false)')
        lines.append(f'        (usegerberattributes true)')
        lines.append(f'        (usegerberadvancedattributes true)')
        lines.append(f'        (creategerberjobfile true)')
        lines.append(f'        (dashed_line_dash_ratio 12.000000)')
        lines.append(f'        (dashed_line_gap_ratio 3.000000)')
        lines.append(f'        (svgprecision 6)')
        lines.append(f'        (plotframeref false)')
        lines.append(f'        (mode 1)')
        lines.append(f'        (useauxorigin false)')
        lines.append(f'        (hpglpennumber 1)')
        lines.append(f'        (hpglpenspeed 20)')
        lines.append(f'        (hpglpendiameter 15.000000)')
        lines.append(f'        (drcpolygon true)')
        lines.append(f'        (drcminmillesspace 0.5)')
        lines.append(f'      )')
        lines.append(f'    )')
        lines.append("")
        
        # 网络段
        lines.append('  (net 0 "")')
        lines.append('  (net 1 "VCC")')
        lines.append('  (net 2 "GND")')
        lines.append("")
        
        # 器件（Footprint占位）
        if placement:
            for comp in placement.components:
                lines.append(f'  (footprint "{comp.footprint}" (layer "F.Cu")')
                lines.append(f'    (tstamp "{generate_uuid()}")')
                lines.append(f'    (at {comp.x:.2f} {comp.y:.2f} {comp.rotation:.0f})')
                lines.append(f'    (fp_text reference "{comp.reference}" (at 0 -2 0)')
                lines.append(f'      (layer "F.SilkS")')
                lines.append(f'      (effects (font (size 1 1) (thickness 0.15))))')
                lines.append(f'    (fp_text value "{comp.value}" (at 0 2 0)')
                lines.append(f'      (layer "F.Fab")')
                lines.append(f'      (effects (font (size 1 1) (thickness 0.15))))')
                lines.append('    (pad "" smd roundrect (at 0 0) (size 1 1) (layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.25))')
                lines.append('  )')
                lines.append("")
        
        # 走线
        if routing:
            for track in routing.tracks:
                lines.append(f'  (segment (start {track.start_x:.2f} {track.start_y:.2f}) (end {track.end_x:.2f} {track.end_y:.2f}) (width {track.width:.2f}) (layer "{track.layer}") (net {1 if track.net == "VCC" else 2}))')
            lines.append("")
        
        lines.append(')')
        
        content = "\n".join(lines)
        Path(output_path).write_text(content, encoding="utf-8")
        
        return output_path
