"""PCB 布局预览渲染器 — 将 KiCad PCB 数据渲染为 SVG/PNG"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional

from ..core.placer import PlacementResult, PlacedComponent
from ..core.router import RoutingResult, TrackSegment, Via
from ..exporters.footprints import get_footprint_def, FootprintDef, PadDef


@dataclass
class PCBRenderConfig:
    """渲染配置"""
    width_px: int = 1400
    height_px: int = 1000
    margin_mm: float = 2.0
    # 颜色主题 (PCB 经典配色)
    bg_color: str = "#1a472a"         # 深绿 PCB 底色
    edge_color: str = "#c0c0c0"       # 板框
    pad_color: str = "#c0c0c0"        # 焊盘银色
    pad_hole_color: str = "#1a1a1a"   # 钻孔黑色
    pad_smd_color: str = "#d4af37"    # SMD 焊盘金色
    track_color: str = "#c0c0c0"      # 走线银色
    track_power_color: str = "#ff6600" # 电源走线橙色
    via_color: str = "#d4af37"        # 过孔金色
    silk_color: str = "#ffffff"       # 丝印白色
    fab_color: str = "#00ff88"        # 装配层绿色
    courtyard_color: str = "#336633"  # 装配框
    body_color: str = "#2d5a2d"       # 器件本体
    text_color: str = "#ffffff"       # 标注文字
    font_size: float = 1.2            # mm


class PCBPreviewRenderer:
    """
    将 PCB 布局渲染为 SVG 文件。
    
    可选转为 PNG (需要 cairosvg 或 Pillow)。
    """
    
    def __init__(
        self,
        placement: PlacementResult,
        routing: Optional[RoutingResult] = None,
        config: Optional[PCBRenderConfig] = None,
    ):
        self.placement = placement
        self.routing = routing
        self.config = config or PCBRenderConfig()
    
    def _mm_to_svg(self, x_mm: float, y_mm: float) -> tuple[float, float]:
        """mm 坐标转 SVG 像素坐标"""
        cfg = self.config
        board_w = self.placement.board_width
        board_h = self.placement.board_height
        scale_x = cfg.width_px / (board_w + 2 * cfg.margin_mm)
        scale_y = cfg.height_px / (board_h + 2 * cfg.margin_mm)
        scale = min(scale_x, scale_y)
        svg_x = (x_mm + cfg.margin_mm) * scale
        svg_y = (y_mm + cfg.margin_mm) * scale
        return svg_x, svg_y
    
    def _mm_to_px(self, mm: float) -> float:
        """mm 转像素（取平均缩放）"""
        board_w = self.placement.board_width
        board_h = self.placement.board_height
        scale = min(
            self.config.width_px / (board_w + 2 * self.config.margin_mm),
            self.config.height_px / (board_h + 2 * self.config.margin_mm),
        )
        return mm * scale
    
    def render_svg(self) -> str:
        """生成 SVG 字符串"""
        cfg = self.config
        board_w = self.placement.board_width
        board_h = self.placement.board_height
        margin = cfg.margin_mm
        
        # 计算视图尺寸
        scale_x = cfg.width_px / (board_w + 2 * margin)
        scale_y = cfg.height_px / (board_h + 2 * margin)
        scale = min(scale_x, scale_y)
        svg_w = (board_w + 2 * margin) * scale
        svg_h = (board_h + 2 * margin) * scale
        
        lines: list[str] = []
        lines.append(f'<?xml version="1.0" encoding="UTF-8"?>')
        lines.append(f'<svg xmlns="http://www.w3.org/2000/svg" '
                     f'width="{svg_w:.1f}" height="{svg_h:.1f}" '
                     f'viewBox="0 0 {svg_w:.1f} {svg_h:.1f}">')
        lines.append(f'  <!-- Generated by code2pcb v0.1.0 -->')
        
        # 样式定义
        lines.append(f'  <style>')
        lines.append(f'    .board {{ fill: {cfg.bg_color}; }}')
        lines.append(f'    .edge {{ fill: none; stroke: {cfg.edge_color}; stroke-width: 2; }}')
        lines.append(f'    .pad {{ fill: {cfg.pad_color}; }}')
        lines.append(f'    .pad-hole {{ fill: {cfg.pad_hole_color}; }}')
        lines.append(f'    .pad-smd {{ fill: {cfg.pad_smd_color}; }}')
        lines.append(f'    .track {{ stroke: {cfg.track_color}; stroke-linecap: round; fill: none; }}')
        lines.append(f'    .track-power {{ stroke: {cfg.track_power_color}; stroke-linecap: round; fill: none; }}')
        lines.append(f'    .via {{ fill: {cfg.via_color}; }}')
        lines.append(f'    .via-hole {{ fill: {cfg.pad_hole_color}; }}')
        lines.append(f'    .silk {{ fill: none; stroke: {cfg.silk_color}; stroke-width: 0.3; }}')
        lines.append(f'    .fab {{ fill: none; stroke: {cfg.fab_color}; stroke-width: 0.2; stroke-dasharray: 0.5,0.5; }}')
        lines.append(f'    .courtyard {{ fill: none; stroke: {cfg.courtyard_color}; stroke-width: 0.15; }}')
        lines.append(f'    .body {{ fill: {cfg.body_color}; stroke: {cfg.silk_color}; stroke-width: 0.3; }}')
        lines.append(f'    .ref {{ fill: {cfg.silk_color}; font-family: monospace; }}')
        lines.append(f'    .val {{ fill: {cfg.fab_color}; font-family: monospace; }}')
        lines.append(f'  </style>')
        
        # PCB 板底色
        x0, y0 = self._mm_to_svg(0, 0)
        x1, y1 = self._mm_to_svg(board_w, board_h)
        lines.append(f'  <rect class="board" x="{x0}" y="{y0}" width="{x1 - x0}" height="{y1 - y0}" rx="2"/>')
        
        # 板框
        lines.append(f'  <rect class="edge" x="{x0}" y="{y0}" width="{x1 - x0}" height="{y1 - y0}" rx="2"/>')
        
        # 安装孔（四角）
        hole_r = 1.5  # mm
        for (hx, hy) in [(margin + 3, margin + 3), (board_w - margin - 3, margin + 3),
                         (margin + 3, board_h - margin - 3), (board_w - margin - 3, board_h - margin - 3)]:
            sx, sy = self._mm_to_svg(hx, hy)
            sr = self._mm_to_px(hole_r)
            lines.append(f'  <circle class="pad-hole" cx="{sx:.1f}" cy="{sy:.1f}" r="{sr:.1f}"/>')
            lines.append(f'  <circle class="pad" cx="{sx:.1f}" cy="{sy:.1f}" r="{sr * 1.5:.1f}" fill="none" stroke="{cfg.pad_color}" stroke-width="{self._mm_to_px(0.3):.1f}"/>')
        
        # 走线（底层，在焊盘下面）
        if self.routing:
            for track in self.routing.tracks:
                is_power = track.net in ("VCC", "GND")
                cls = "track-power" if is_power else "track"
                w = self._mm_to_px(track.width)
                sx1, sy1 = self._mm_to_svg(track.start_x, track.start_y)
                sx2, sy2 = self._mm_to_svg(track.end_x, track.end_y)
                lines.append(f'  <line class="{cls}" x1="{sx1:.1f}" y1="{sy1:.1f}" x2="{sx2:.1f}" y2="{sy2:.1f}" stroke-width="{w:.1f}"/>')
            
            # 过孔
            for via in self.routing.vias:
                sx, sy = self._mm_to_svg(via.x, via.y)
                r = self._mm_to_px(via.size / 2)
                rh = self._mm_to_px(via.drill / 2)
                lines.append(f'  <circle class="via" cx="{sx:.1f}" cy="{sy:.1f}" r="{r:.1f}"/>')
                lines.append(f'  <circle class="via-hole" cx="{sx:.1f}" cy="{sy:.1f}" r="{rh:.1f}"/>')
        
        # 器件
        for comp in self.placement.components:
            self._render_footprint(lines, comp)
        
        lines.append('</svg>')
        return "\n".join(lines)
    
    def _render_footprint(self, lines: list[str], comp: PlacedComponent):
        """渲染单个器件封装"""
        fp_def = get_footprint_def(comp.footprint)
        if not fp_def:
            return
        
        cx, cy = comp.x, comp.y  # mm
        rotation = comp.rotation
        font_size = self.config.font_size
        
        # Court yard
        cx_c, cy_c = fp_def.courtyard[:2]
        w_c, h_c = fp_def.courtyard[2], fp_def.courtyard[3]
        sx, sy = self._mm_to_svg(cx + cx_c, cy + cy_c)
        sw, sh = self._mm_to_px(w_c), self._mm_to_px(h_c)
        lines.append(f'  <rect class="courtyard" x="{sx:.1f}" y="{sy:.1f}" width="{sw:.1f}" height="{sh:.1f}" transform="rotate({rotation},{self._mm_to_svg(cx, cy)[0]:.1f},{self._mm_to_svg(cx, cy)[1]:.1f})"/>')
        
        # Body rectangle
        if fp_def.body_rect:
            bx, by, bw, bh = fp_def.body_rect
            sx, sy = self._mm_to_svg(cx + bx, cy + by)
            sw, sh = self._mm_to_px(bw), self._mm_to_px(bh)
            ccx, ccy = self._mm_to_svg(cx, cy)
            lines.append(f'  <rect class="body" x="{sx:.1f}" y="{sy:.1f}" width="{sw:.1f}" height="{sh:.1f}" rx="1" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
        
        # Pin 1 marker (small dot)
        if fp_def.pads:
            p1 = fp_def.pads[0]
            px, py = cx + p1.at[0], cy + p1.at[1]
            sx, sy = self._mm_to_svg(px, py)
            r = self._mm_to_px(0.3)
            ccx, ccy = self._mm_to_svg(cx, cy)
            lines.append(f'  <circle class="silk" cx="{sx:.1f}" cy="{sy:.1f}" r="{r:.1f}" fill="{self.config.silk_color}" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
        
        # Pads
        for pad in fp_def.pads:
            px = cx + pad.at[0]
            py = cy + pad.at[1]
            pw = pad.size[0]
            ph = pad.size[1]
            sx, sy = self._mm_to_svg(px, py)
            sw = self._mm_to_px(pw)
            sh = self._mm_to_px(ph)
            ccx, ccy = self._mm_to_svg(cx, cy)
            
            if pad.pad_type == "tht":
                # THT: 外圈 + 内孔
                lines.append(f'  <circle class="pad" cx="{sx:.1f}" cy="{sy:.1f}" r="{sw/2:.1f}" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
                if pad.drill:
                    rh = self._mm_to_px(pad.drill / 2)
                    lines.append(f'  <circle class="pad-hole" cx="{sx:.1f}" cy="{sy:.1f}" r="{rh:.1f}" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
            elif pad.shape == "circle":
                r = sw / 2
                lines.append(f'  <circle class="pad-smd" cx="{sx:.1f}" cy="{sy:.1f}" r="{r:.1f}" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
            else:
                # SMD rect/roundrect
                rx = 0.2 if pad.shape == "roundrect" else 0
                lines.append(f'  <rect class="pad-smd" x="{sx - sw/2:.1f}" y="{sy - sh/2:.1f}" width="{sw:.1f}" height="{sh:.1f}" rx="{rx:.1f}" transform="rotate({rotation},{ccx:.1f},{ccy:.1f})"/>')
        
        # Reference text
        ref_x = cx + fp_def.ref_offset[0]
        ref_y = cy + fp_def.ref_offset[1]
        sx, sy = self._mm_to_svg(ref_x, ref_y)
        fs = self._mm_to_px(font_size)
        lines.append(f'  <text class="ref" x="{sx:.1f}" y="{sy:.1f}" font-size="{fs:.1f}" text-anchor="middle">{comp.reference}</text>')
        
        # Value text
        val_x = cx + fp_def.value_offset[0]
        val_y = cy + fp_def.value_offset[1]
        sx, sy = self._mm_to_svg(val_x, val_y)
        lines.append(f'  <text class="val" x="{sx:.1f}" y="{sy:.1f}" font-size="{fs * 0.8:.1f}" text-anchor="middle">{comp.value}</text>')
    
    def save_svg(self, path: str) -> str:
        """保存 SVG 文件"""
        svg = self.render_svg()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(svg)
        return path
    
    def save_png(self, path: str) -> str:
        """保存 PNG 文件 (需要 cairosvg 或 Pillow)"""
        try:
            import cairosvg
            svg = self.render_svg()
            cairosvg.svg2png(bytestring=svg.encode(), write_to=path, output_width=self.config.width_px, output_height=self.config.height_px)
            return path
        except ImportError:
            pass
        
        try:
            from PIL import Image, ImageDraw, ImageFont
            self._render_pil(path)
            return path
        except ImportError:
            raise RuntimeError(
                "PNG export requires cairosvg or Pillow. "
                "Install with: pip install cairosvg  OR  pip install Pillow"
            )
    
    def _render_pil(self, path: str):
        """用 Pillow 直接渲染（不依赖 SVG）"""
        from PIL import Image, ImageDraw, ImageFont
        
        cfg = self.config
        img = Image.new("RGB", (cfg.width_px, cfg.height_px), cfg.bg_color)
        draw = ImageDraw.Draw(img)
        
        board_w = self.placement.board_width
        board_h = self.placement.board_height
        margin = cfg.margin_mm
        
        def to_px(x_mm, y_mm):
            scale_x = cfg.width_px / (board_w + 2 * margin)
            scale_y = cfg.height_px / (board_h + 2 * margin)
            scale = min(scale_x, scale_y)
            px = int((x_mm + margin) * scale)
            py = int((y_mm + margin) * scale)
            return px, py
        
        def mm_to_px(mm):
            scale = min(cfg.width_px / (board_w + 2 * margin),
                       cfg.height_px / (board_h + 2 * margin))
            return max(1, int(mm * scale))
        
        # 板框
        x0, y0 = to_px(0, 0)
        x1, y1 = to_px(board_w, board_h)
        draw.rectangle([x0, y0, x1, y1], outline=cfg.edge_color, width=2)
        
        # 走线
        if self.routing:
            for track in self.routing.tracks:
                color = cfg.track_power_color if track.net in ("VCC", "GND") else cfg.track_color
                w = max(1, mm_to_px(track.width))
                p1 = to_px(track.start_x, track.start_y)
                p2 = to_px(track.end_x, track.end_y)
                draw.line([p1, p2], fill=color, width=w)
            
            for via in self.routing.vias:
                px, py = to_px(via.x, via.y)
                r = mm_to_px(via.size / 2)
                rh = mm_to_px(via.drill / 2)
                draw.ellipse([px-r, py-r, px+r, py+r], fill=cfg.via_color)
                draw.ellipse([px-rh, py-rh, px+rh, py+rh], fill=cfg.pad_hole_color)
        
        # 器件
        for comp in self.placement.components:
            fp_def = get_footprint_def(comp.footprint)
            if not fp_def:
                continue
            
            cx, cy = comp.x, comp.y
            
            # Body
            if fp_def.body_rect:
                bx, by, bw, bh = fp_def.body_rect
                px0, py0 = to_px(cx + bx, cy + by)
                px1, py1 = to_px(cx + bx + bw, cy + by + bh)
                draw.rectangle([px0, py0, px1, py1], fill=cfg.body_color, outline=cfg.silk_color, width=1)
            
            # Pads
            for pad in fp_def.pads:
                px, py = cx + pad.at[0], cy + pad.at[1]
                pw, ph = pad.size
                sx, sy = to_px(px, py)
                sw, sh = mm_to_px(pw), mm_to_px(ph)
                
                if pad.pad_type == "tht":
                    r = sw // 2
                    draw.ellipse([sx-r, sy-r, sx+r, sy+r], fill=cfg.pad_color)
                    if pad.drill:
                        rh = mm_to_px(pad.drill / 2)
                        draw.ellipse([sx-rh, sy-rh, sx+rh, sy+rh], fill=cfg.pad_hole_color)
                else:
                    draw.rectangle([sx-sw//2, sy-sh//2, sx+sw//2, sy+sh//2], fill=cfg.pad_smd_color)
            
            # Pin 1 marker
            if fp_def.pads:
                p1 = fp_def.pads[0]
                mx, my = to_px(cx + p1.at[0], cy + p1.at[1])
                r = max(1, mm_to_px(0.3))
                draw.ellipse([mx-r, my-r, mx+r, my+r], fill=cfg.silk_color)
            
            # Reference
            rx, ry = to_px(cx + fp_def.ref_offset[0], cy + fp_def.ref_offset[1])
            fs = max(8, mm_to_px(cfg.font_size))
            try:
                font = ImageFont.truetype("/System/Library/Fonts/Menlo.ttc", fs)
            except (OSError, IOError):
                try:
                    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", fs)
                except (OSError, IOError):
                    font = ImageFont.load_default()
            draw.text((rx, ry - fs), comp.reference, fill=cfg.silk_color, anchor="mm", font=font)
        
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        img.save(path)
